### ISSUE TITLE
符号错了，分号 应该是逗号

### ISSUE THREAD

**Issue by lewislau86** [WTFAcademy/WTF-JavaScript#28]
习题
补全下面的 isDev 函数，完成逻辑，当输入的对象 obj 的 isDeveloper 属性为 true 时，返回 true，否则返回 false。

function isDev(obj){

}

const obj1 = {
  name: "0xAA";
  isDeveloper: true;
}
const obj2 = {
  name: "Trump";
}
console.log(isDev(obj1)); // 应该输出 true
console.log(isDev(obj2)); // 应该输出 false

**Comment by AmazingAng** [comment]
的确错了，你提个pr把
